- 대규모 숫자계산을 해주는 라이브러리다.
- 계산식을 먼저 만들어 놓고 데이터를 하나하나 넣으며 실행하는 구조이다. 
- 영상처리 기능도 있으며 그 때는 OpenCV라이브러리 등과 함께 사용한다.
- c = a+b 라는 의미는 'a+b라는 연산을 c라고 정의한다' 라는 의미이다.( 파이썬에서는 a+b를 c에 대입한다는 의미임)
텐서플로우1과 2를 동시에 사용하고 싶다면 파이썬 3.6. /3.7 버전을 사용하자,
 
텐서플로우는 설치 후에 노트북을 재실행해야지 제대로 실행이 된다.

pip install tensorflow       => 최신 버전이 깔림
pip install tensorflow==1.15.0 
pip install protobuf==3.20.*   # 1.15.0 버전이 오류뜨면 해결하기

pip install --upgrade tensorflow    =>원하는 버전으로 업그레이드하기  

- 현재는 1점대 버전이다. 



In [1]:
import tensorflow as tf

### 예제 1

In [2]:
# 상수 노드 정의(constant) / 텐서플로우 1점대 버전에서 등호는 정의한다는 의미이다. 
a = tf.constant(1.0) 
b = tf.constant(2.0)
c = tf.constant([ [1.0, 2.0], [3.0, 4.0] ])

print(a) 
print(a+b)
print(c)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)
Tensor("Const_2:0", shape=(2, 2), dtype=float32)


In [3]:
# 세션 (session) 을 만들고 노드간의 텐서 연산 실행
# sess = tf.Session() 
sess = tf.compat.v1.Session()
print(sess.run([a, b])) 
print(sess.run(c))
print(sess.run([a+b]))
print(sess.run(c+1.0)) # numpy의 broadcast연산 수행

# 세션 close
sess.close() 

[1.0, 2.0]
[[1. 2.]
 [3. 4.]]
[3.0]
[[2. 3.]
 [4. 5.]]


### 예제2

In [4]:
# 상수 정의하기 --- (※2)
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

# 연산 정의하기 --- (※3)
calc1_op = a + b * c  # a + b * c을 calc1_op로 정의하기 
calc2_op = (a + b) * c

# 세션 시작하기 --- (※4)
sess = tf.compat.v1.Session()
res1 = sess.run(calc1_op) # 식 평가하기
print(res1)
res2 = sess.run(calc2_op) # 식 평가하기
print(res2)
# 세션 close
sess.close() 

14
20


### 플레이스홀더 노드(placeholder node)

In [5]:
# ex1
# 플레이스홀더 노드 정의
a = tf.placeholder(tf.float32) 
b = tf.placeholder(tf.float32) 
c = a + b 

# 세션 (session) 을 만들고 플레이스홀더 노드를 통해 값 입력받음
sess = tf.compat.v1.Session()
print(sess.run(c, feed_dict={ a: 1.0, b: 3.0 })) 
print(sess.run(c, feed_dict={ a: [1.0, 2.0], b: [3.0, 4.0] })) 

# 세션 close
sess.close() 


4.0
[4. 6.]


In [6]:
# ex2
# 플레이스홀더 정의하기 --- (※1)
a = tf.placeholder(tf.int32, [3]) # 정수 자료형 3개를 가진 배열
# 배열을 모든 값을 2배하는 연산 정의하기 --- (※2)
# b는 상수 2를 정의
b = tf.constant(2)
x2_op = a * b

# 세션 시작하기 --- (※3)
sess = tf.compat.v1.Session()
# 플레이스홀더에 값을 넣고 실행하기 --- (※4)
r1 = sess.run(x2_op, feed_dict={ a:[1, 2, 3] })
print(r1)
r2 = sess.run(x2_op, feed_dict={ a:[10, 20, 10] })
print(r2)

# 세션 close
sess.close()

[2 4 6]
[20 40 20]


### 변수노드
- 변수: 값을 변경가능(상수는 변경불가)

In [7]:
# ex1)

# 값이 업데이트되는 변수노드 정의
W1 = tf.Variable(tf.random.normal([1]))  # random.normal 상수 하나를 정해준다고 생각하자
b1 = tf.Variable(tf.random.normal([1]))
W2 = tf.Variable(tf.random.normal([1, 2])) 
b2 = tf.Variable(tf.random.normal([1, 2]))

# 세션 생성
sess = tf.compat.v1.Session()


In [8]:
# 변수노드 값 초기화. 변수노드를 정의했다면 반드시 필요함(tf.compat.v1.global_variables_initializer 이거를 만나야만이 변수에 대한 초기화 됨.)
sess.run( tf.compat.v1.global_variables_initializer()) 
for step in range(3):
    W1 = W1 - step 
    b1 = b1 - step
    W2 = W2 - step 
    b2 = b2 - step
    print("step = ", step, ", W1 = ", sess.run(W1), ", b1 = ", sess.run(b1))
    print("step = ", step, ", W2 = ", sess.run(W2), ", b2 = ", sess.run(b2))
sess.close() 

step =  0 , W1 =  [1.4911053] , b1 =  [-0.3431087]
step =  0 , W2 =  [[1.124854  1.5006057]] , b2 =  [[-1.3822865  -0.18949392]]
step =  1 , W1 =  [0.49110532] , b1 =  [-1.3431087]
step =  1 , W2 =  [[0.12485397 0.5006057 ]] , b2 =  [[-2.3822865 -1.1894939]]
step =  2 , W1 =  [-1.5088947] , b1 =  [-3.3431087]
step =  2 , W2 =  [[-1.875146  -1.4993943]] , b2 =  [[-4.3822865 -3.189494 ]]


In [9]:
# ex 2

# feeding 값 선언
input_data = [1,2,3,4,5] #리스트 객체(여기 부분은 일반 파이썬 소스코드임)
# placeholder 변수 선언
x = tf.placeholder(dtype=tf.float32)
# W = 2라는 값 선언
W = tf.Variable([2],dtype=tf.float32) # 2라는 값으로 초기화가 됨
y = W * x

In [10]:
sess = tf.compat.v1.Session()
# 변수 초기화 코드를 세션에 전달한다.
sess.run(tf.compat.v1.global_variables_initializer())
# y 그래프에 input_date feeding 하면서 세션 실행한다.

In [11]:
result = sess.run(y,feed_dict={x:input_data})
print(result) 
# 세션 close
sess.close() 

[ 2.  4.  6.  8. 10.]


In [12]:
# ex3
import tensorflow as tf
# 상수 정의하기 --- (※1)
# name을 이용해서 별칭 부여도 가능
a = tf.constant(120)
b = tf.constant(130)
c = tf.constant(140)


# 변수 정의하기 --- (※2)
# 변수 v를 정의하고 초기치 0을 저장
v = tf.Variable(0) 

In [13]:
# 데이터 플로우 그래프 정의하기 --- (※3)
calc_op = a + b + c
assign_op = tf.compat.v1.assign(v, calc_op)


In [14]:
# 세션 실행하기 --- (※4)
sess = tf.compat.v1.Session()
# tf.global_variables_initializer() 
# 메소드를 사용하여 세션에 초기화 연산을 수행해야 하며, 변수에 메모리를 할당하고 초기값을 설정하는 역할을 한다

In [15]:
sess.run(tf.global_variables_initializer())
sess.run(assign_op)
# v의 내용 출력하기 --- (※5)
print( sess.run(v) ) 
sess.close() 


390


### 여기부터가 머신러닝과 관련된 작업이다. (ex4) // 잘 쓰지는 않는다고 함

In [16]:
import pandas as pd
import numpy as np
import tensorflow as tf
csv = pd.read_csv("data/bmi.csv")

In [17]:
# 데이터 정규화 --- (※2)
csv["height"] = csv["height"] / 200 # 최대 키가 200
csv["weight"] = csv["weight"] / 100 # 최대 몸무게가 100으로 가정함

In [28]:
# 레이블을 배열로 변환하기 --- (※3)
# - thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
bclass = {"thin": [1,0,0], "normal": [0,1,0], "fat": [0,0,1]} # 원핫인코딩 방식이다. 
csv["label_pat"] = csv["label"].apply(lambda x : np.array(bclass[x]))
csv

height  weight   label  label_pat
0       0.710    0.62     fat  [0, 0, 1]
1       0.710    0.73     fat  [0, 0, 1]
2       0.885    0.61  normal  [0, 1, 0]
3       0.935    0.48    thin  [1, 0, 0]
4       0.765    0.60     fat  [0, 0, 1]
...       ...     ...     ...        ...
19995   0.610    0.58     fat  [0, 0, 1]
19996   0.965    0.69  normal  [0, 1, 0]
19997   0.965    0.37    thin  [1, 0, 0]
19998   0.975    0.51    thin  [1, 0, 0]
19999   0.815    0.67  normal  [0, 1, 0]

[20000 rows x 4 columns]

In [19]:
# 테스트를 위한 데이터 분류 --- (※4)
test_csv = csv[15000:20000] # 인위적으로 분할함
test_pat = test_csv[["weight","height"]]
test_ans = list(test_csv["label_pat"]) 

In [20]:
# 플레이스홀더 선언하기--- (※5)
x = tf.placeholder(tf.float32, [None, 2]) # 키와 몸무게 데이터 넣기.2차원구조
y_ = tf.placeholder(tf.float32, [None, 3]) # 열이 3인 이유는 
sess.close() 

In [21]:
# 변수 선언하기 --- (※6)
W = tf.Variable(tf.zeros([2, 3])); # 가중치
b = tf.Variable(tf.zeros([3])); # 바이어스

In [22]:
# 소프트맥스 회귀 정의하기 --- (※7)
y = tf.nn.softmax(tf.matmul(x, W) + b)  # 행렬 간 곱셈연산을 하는 함수가 matmul이다.

In [23]:
# 모델 훈련하기 --- (※8)
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y, labels=y_)) 
# cross_entropy => 손실값을 계산하는 과정이다.  // 분류작업에 사용되는 손실값(cross entropy)/ 회귀모델에 사용되는 손실값(평균제곱오차)
# GradientDescentOptimizer : 경사하강법으로 손실 함수를 최소화하는 모델 파라미터를 찾기 위해 사용
# 0.01은 학습률을 의미
optimizer =  tf.compat.v1.train.GradientDescentOptimizer(0.01) # w와 b를 자동으로 설정함
train = optimizer.minimize(cross_entropy) # 이 연산을 수행하면 손실값이 최소화 될 수 있는 w와 b를 구할 수 있다.


In [24]:
# 정답률 구하기
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32)) # tf.cast() : 캐스트 연산에 사용

In [25]:
# 세션 시작하기
sess = tf.compat.v1.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화하기

In [26]:
# 학습시키기
for step in range(15000):
    i = (step * 100) % 15000
    rows = csv[1 + i : 1 + i + 100] # 15000개의 데이터가 있으면 일정하게 쪼갠다.
    x_pat = rows[["weight","height"]]
    y_ans = list(rows["label_pat"])
    fd = {x: x_pat, y_: y_ans}
    sess.run(train, feed_dict=fd)
    if step % 500 == 0:
        cre = sess.run(cross_entropy, feed_dict=fd)
        acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
        print("step=", step, "cre=", cre, "acc=", acc)

step= 0 cre= 1.098595 acc= 0.3242
step= 500 cre= 1.0949001 acc= 0.3684
step= 1000 cre= 1.0968362 acc= 0.3684
step= 1500 cre= 1.0890875 acc= 0.3684
step= 2000 cre= 1.0854574 acc= 0.3684
step= 2500 cre= 1.0907798 acc= 0.3684
step= 3000 cre= 1.0794799 acc= 0.3772
step= 3500 cre= 1.0763575 acc= 0.4024
step= 4000 cre= 1.082489 acc= 0.433
step= 4500 cre= 1.0693377 acc= 0.4796
step= 5000 cre= 1.0670123 acc= 0.5142
step= 5500 cre= 1.0734547 acc= 0.5468
step= 6000 cre= 1.058941 acc= 0.5828
step= 6500 cre= 1.0574982 acc= 0.6054
step= 7000 cre= 1.064285 acc= 0.6246
step= 7500 cre= 1.0485251 acc= 0.6442
step= 8000 cre= 1.0479634 acc= 0.6528
step= 8500 cre= 1.0552124 acc= 0.659
step= 9000 cre= 1.038259 acc= 0.6674
step= 9500 cre= 1.0385478 acc= 0.6726
step= 10000 cre= 1.0463612 acc= 0.6774
step= 10500 cre= 1.0282755 acc= 0.6812
step= 11000 cre= 1.02937 acc= 0.683
step= 11500 cre= 1.0378207 acc= 0.6846
step= 12000 cre= 1.018677 acc= 0.6868
step= 12500 cre= 1.0205232 acc= 0.6872
step= 13000 cre= 1.02

In [27]:
# 최종적인 정답률 구하기
acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
print("정답률 =", acc)

정답률 = 0.6906


## 주로 사용하는 버전은 텐서플로 2이다. 